CREATE TABLE IF NOT EXISTS User (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  email VARCHAR(40) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS GameProfile (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  userId INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (userId) REFERENCES User(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS Class (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS Category (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  classId INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (classId) REFERENCES Class(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS Question (
  id INT(11) NOT NULL AUTO_INCREMENT,
  question VARCHAR(100) NOT NULL,
  answer VARCHAR(100) NOT NULL,
  difficulty INT(11) NOT NULL,
  categoryId INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (categoryId) REFERENCES Category(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS QuestionGameProfile (
  questionId INT(11) NOT NULL,
  gameProfileId INT(11) NOT NULL,
  PRIMARY KEY (questionId, gameProfileId),
  FOREIGN KEY (questionId) REFERENCES Question(id),
  FOREIGN KEY (gameProfileId) REFERENCES GameProfile(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS CategoryGameProfile (
  categoryId INT(11) NOT NULL,
  gameProfileId INT(11) NOT NULL,
  PRIMARY KEY (categoryId, gameProfileId),
  FOREIGN KEY (categoryId) REFERENCES Category(id),
  FOREIGN KEY (gameProfileId) REFERENCES GameProfile(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS ClassGameProfile (
  classId INT(11) NOT NULL,
  gameProfileId INT(11) NOT NULL,
  PRIMARY KEY (classId, gameProfileId),
  FOREIGN KEY (classId) REFERENCES Class(id),
  FOREIGN KEY (gameProfileId) REFERENCES GameProfile(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

