CREATE TABLE IF NOT EXISTS User (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  email VARCHAR(40) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS GameProfile (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  userId INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS Class (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS Category (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  classId INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (classId) REFERENCES Class(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS Question (
  id INT(11) NOT NULL AUTO_INCREMENT,
  question VARCHAR(100) NOT NULL,
  answer VARCHAR(100) NOT NULL,
  difficulty INT(11) NOT NULL,
  categoryId INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS QuestionGameProfile (
  questionId INT(11) NOT NULL,
  gameProfileId INT(11) NOT NULL,
  PRIMARY KEY (questionId, gameProfileId),
  FOREIGN KEY (questionId) REFERENCES Question(id) ON DELETE CASCADE,
  FOREIGN KEY (gameProfileId) REFERENCES GameProfile(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS CategoryGameProfile (
  categoryId INT(11) NOT NULL,
  gameProfileId INT(11) NOT NULL,
  PRIMARY KEY (categoryId, gameProfileId),
  FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE CASCADE,
  FOREIGN KEY (gameProfileId) REFERENCES GameProfile(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS ClassGameProfile (
  classId INT(11) NOT NULL,
  gameProfileId INT(11) NOT NULL,
  PRIMARY KEY (classId, gameProfileId),
  FOREIGN KEY (classId) REFERENCES Class(id) ON DELETE CASCADE,
  FOREIGN KEY (gameProfileId) REFERENCES GameProfile(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `gameresults` (
	id MEDIUMINT NOT NULL AUTO_INCREMENT,
	winner INT NULL,
	date DATE NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `team` (
	id INT NULL AUTO_INCREMENT,
	gameId INT NULL,
	score INT NULL,
	name VARCHAR(50) NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `participant` (
	id INT NULL AUTO_INCREMENT,
	name VARCHAR(50) NULL,
	teamId INT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


